// ============================================================
// EGS PRODUCTS — Edit this file to add/remove/update products
// ============================================================

const PRODUCTS = [

  // ===== SONOFF =====
  {brand:'sonoff',id:'basicr2',featured:true,cat:'switch',tag:'BESTSELLER',tc:'blue',name:'Basic Smart Switch',model:'Sonoff BASICR2',price:0,pd:'Contact for price',img:'basicr2_real',desc:'WiFi relay switch. Installs behind any wall switch or appliance. Remote control, voice control, scheduling. Magic Switch Mode keeps app control even when wall switch is off. 10A / 2200W.',specs:[['Protocol','Wi-Fi 2.4GHz'],['Max Load','10A / 2200W'],['Input','100–240V AC'],['Size','90×41×27mm']]},
  {brand:'sonoff',id:'minir2',featured:true,cat:'switch',tag:'MINI',tc:'green',name:'Mini Smart Switch',model:'Sonoff MINI R2',price:0,pd:'Contact for price',img:'minir2_real',desc:'Designed for Lebanese wiring — installs hidden behind your existing wall switch. No neutral wire required. Your switch stays exactly as it looks but now you control it from your phone. Fits inside any standard wall box.',specs:[['Protocol','Wi-Fi 2.4GHz'],['Max Load','10A / 2200W'],['Size','48×30×46mm'],['Neutral','Optional']]},
  {brand:'sonoff',id:'dualr3',featured:true,cat:'switch',tag:'',tc:'',name:'Dual Relay + Power Meter',model:'Sonoff DUALR3',price:0,pd:'Contact for price',img:'dualr3',desc:'Two independent relay channels, each with power metering. Ideal for curtains, shutters, or 2 separate circuits.',specs:[['Channels','2 Independent'],['Max Load','10A/gang, 15A total'],['Power Meter','Per channel'],['Protocol','Wi-Fi 2.4GHz']]},
  {brand:'sonoff',id:'powr3',cat:'switch',tag:'25A',tc:'gold',name:'Power Meter Switch 25A',model:'Sonoff POWR3',price:0,pd:'Contact for price',img:'powr3',desc:'High-power smart switch up to 25A / 5500W. Perfect for generator monitoring, heavy appliances and DIN rail. Overload protection included.',specs:[['Max Load','25A / 5500W'],['Protocol','Wi-Fi 2.4GHz'],['Protection','Overload, Voltage, Current'],['Size','166×125×49mm']]},
  {brand:'sonoff',id:'4chpro',cat:'switch',tag:'',tc:'',name:'4-Gang Smart Switch',model:'Sonoff 4CHPRO R3',price:0,pd:'Contact for price',img:'4chpro',desc:'Control 4 appliances independently. WiFi + RF 433MHz. Inching, self-locking and interlock modes. Perfect for 4-circuit panels.',specs:[['Channels','4 Independent'],['Control','WiFi + RF 433MHz'],['Max Load','10A per gang'],['Modes','Normal/Inching/Interlock']]},
  {brand:'sonoff',id:'s26',featured:true,cat:'plug',tag:'ENERGY MONITOR',tc:'gold',name:'Smart Plug + Energy Monitor',model:'Sonoff S26',price:0,pd:'Contact for price',img:'s26',desc:'Plug-in smart socket (EU/UK formats). Real-time energy monitoring with daily and monthly stats. Overload protection.',specs:[['Protocol','Wi-Fi 2.4GHz'],['Max Load','10A / 2200W'],['Types','EU, UK, US, AU'],['Power Monitor','Yes']]},
  {brand:'sonoff',id:'led_strip',cat:'lighting',tag:'RGB',tc:'gold',name:'Smart LED Light Strip',model:'Sonoff L1 (2M/5M)',price:0,pd:'Contact for price',img:'led_strip',desc:'WiFi LED strip with 16 million colors. Music reactive mode. Waterproof, flexible, self-adhesive. App, BT or IR remote control.',specs:[['Colors','16M RGB'],['Sizes','2M or 5M'],['Waterproof','Yes'],['Control','App / BT / IR']]},
  {brand:'sonoff',id:'bulb_white',cat:'lighting',tag:'',tc:'',name:'Smart LED Bulb (White)',model:'Sonoff B02-B-A60',price:0,pd:'Contact for price',img:'bulb_white',desc:'WiFi smart bulb, warm to cool white (2700K–6500K). Stepless dimming. E27 base. 9W, 806 lumens, 10,000 hour lifespan.',specs:[['Base','E27'],['Power','9W / 806lm'],['CCT','2700K–6500K'],['Life','~10,000h']]},
  {brand:'sonoff',id:'bulb_rgb',cat:'lighting',tag:'RGB',tc:'gold',name:'Smart RGB Color Bulb',model:'Sonoff B05-BL-A60',price:0,pd:'Contact for price',img:'bulb_rgb',desc:'Full RGB color bulb with 16 million colors. Stepless dimming. App and voice control. Create dynamic lighting scenes.',specs:[['Base','E27'],['Power','9W / 806lm'],['Colors','Full RGB + White'],['Control','App + Voice']]},
  {brand:'sonoff',id:'rf_bridge',cat:'security',tag:'',tc:'',name:'RF Bridge — Sensor Hub',model:'Sonoff RF BridgeR2',price:0,pd:'Contact for price',img:'rf_bridge_real',desc:'WiFi bridge connecting 433MHz sensors to eWeLink app. Supports motion, door, and remote sensors. One hub for multiple devices.',specs:[['Wireless','WiFi + 433MHz'],['Input','5V 1A'],['Sensors','Multiple supported'],['Size','64×64×23mm']]},
  {brand:'sonoff',id:'pir_motion',cat:'sensor',tag:'',tc:'',name:'Motion Sensor',model:'Sonoff PIR3-RF',price:0,pd:'Contact for price',img:'pir_motion_real',desc:'Wireless PIR motion sensor. 8m range, 100° angle. Works with RF Bridge to trigger lights or alarms. Battery powered.',specs:[['Range','Up to 8m'],['Angle','100°'],['Battery','CR2450'],['Protocol','RF 433MHz']]},
  {brand:'sonoff',id:'door_sensor',cat:'sensor',tag:'',tc:'',name:'Door / Window Sensor',model:'Sonoff DW2 Wi-Fi',price:0,pd:'Contact for price',img:'door_sensor_real',desc:'Direct WiFi door/window sensor — no RF bridge needed. Instant phone alert on open. Trigger smart scenes on events.',specs:[['Protocol','Wi-Fi 2.4GHz'],['Battery','2× AAA 1.5V'],['Gap','< 5mm'],['Alerts','Push notification']]},
  {brand:'sonoff',id:'snzb_01',cat:'sensor',tag:'ZIGBEE',tc:'green',name:'Zigbee Sensors',model:'Sonoff SNZB Series',price:0,pd:'Contact for price',img:'snzb_01',desc:'Zigbee sensor range: wireless button (SNZB-01), temp & humidity (SNZB-02), motion (SNZB-03), door/window (SNZB-04). Requires Zigbee hub.',specs:[['Protocol','Zigbee 3.0'],['Battery','CR2450 / CR2032'],['Hub Required','Yes'],['Range','~30m indoor']]},
  {brand:'sonoff',id:'tx_ultimate',cat:'switch',tag:'RGB',tc:'gold',featured:true,name:'TX Ultimate Smart Touch Switch',model:'SONOFF TX Ultimate 120',price:0,pd:'Contact for price',img:'SONOFF TX-1gang',desc:'Full touch control with edge-lit RGB accents, motion awareness, and motorized shading control. Tactile sound and vibration feedback. Smart automations, timers, and scene control. Works with full SONOFF ecosystem.',specs:[['Protocol','Wi-Fi 2.4GHz'],['Max Load','16A total'],['RGB','Edge-lit LED Ring'],['Feedback','Sound + Vibration']],variants:{gangs:['1 Gang','2 Gang','3 Gang','4 Gang']},variantImgs:{'1 Gang_White':'SONOFF TX-1gang','2 Gang_White':'SONOFF TX-2gang','3 Gang_White':'SONOFF TX-3gang','4 Gang_White':'SONOFF TX-4gang'},variantPrices:{'1 Gang':'Contact for price','2 Gang':'Contact for price','3 Gang':'Contact for price','4 Gang':'Contact for price'}},

  // ===== TUYA PRODUCTS =====
  {brand:'tuya',id:'ty_control_panel',cat:'security',tag:'PREMIUM ⭐',tc:'blue',name:'Smart Control Panel 7"',model:'Tuya TPP06 Mini',price:0,pd:'Contact for price',img:'control_panel',desc:'All-in-one smart home control panel. 3.5" touch screen with built-in Bluetooth Mesh and IR gateway. Control 110+ device categories.',specs:[['Screen','3.5 inch Touch'],['Gateway','BT Mesh + IR Built-in'],['Protocols','Wi-Fi + BT + IR'],['Install','EU Wall Mount']]},
  {brand:'tuya',id:'ty_panel_pro',cat:'security',tag:'PREMIUM ⭐',tc:'blue',name:'Smart Control Panel Pro 8"',model:'Tuya TPA08-M3',price:0,pd:'Contact for price',img:'sm_panel_pro',desc:'Premium 8-inch Android smart home panel with Alexa built-in. Zigbee and Bluetooth Mesh gateway, 2 relay gangs, dual speakers.',specs:[['Screen','8 inch Android'],['Voice','Alexa Built-in'],['Gateway','Zigbee + BT Mesh'],['Relay','2 Gang']]},
  {brand:'tuya',id:'ty_doorbell',cat:'security',tag:'2K ⭐',tc:'blue',name:'2K Smart Video Doorbell',model:'Tuya SC162-WCD3',price:0,pd:'Contact for price',img:'doorbell_2k',desc:'2K HD video doorbell with indoor chime. 170° wide angle lens. Push notifications for humans and packages. Battery powered with IP65 rating.',specs:[['Resolution','2K 1536×2048'],['Lens','170° Wide Angle'],['Battery','5200mAh IP65'],['Detection','Human + Package']]},
  {brand:'tuya',id:'ty_door_lock',featured:true,cat:'security',tag:'FACE ID ⭐',tc:'gold',name:'Smart Video Door Lock',model:'Tuya I8 Smart Video Lock',price:0,pd:'Contact for price',img:'door_lock_ty',desc:'Premium smart door lock with video camera. Unlock via Face ID, fingerprint, PIN, card, app or key. Store 300 fingerprints/PINs/cards.',specs:[['Unlock','Face/Fingerprint/PIN/Card/App'],['Video','Live Communication'],['Storage','300 Users'],['Battery','4200mAh']]},
  {brand:'tuya',id:'ty_mcb',cat:'security',tag:'CIRCUIT ⭐',tc:'blue',name:'AI Smart Circuit Breaker',model:'Tuya AICB2SP',price:0,pd:'Contact for price',img:'circuit_breaker',desc:'AI-powered smart circuit breaker with remote on/off, real-time energy monitoring and overload protection. Available in 1P/2P/3P/4P up to 100A. Essential for Lebanon generator management.',specs:[['Rating','6A to 100A'],['Poles','1P/2P/3P/4P'],['Monitoring','Voltage/Current/Power'],['Lifespan','20,000 operations']]},
  {brand:'tuya',id:'ty_energy_meter',cat:'switch',tag:'ENERGY',tc:'gold',name:'Smart Energy Meter',model:'Tuya DAC21C Series',price:0,pd:'Contact for price',img:'energy-meter',desc:'DIN rail smart energy meter with LCD display. Bi-directional metering, daily and monthly stats. Perfect for generator monitoring in Lebanon.',specs:[['Display','LCD'],['Metering','Bi-directional'],['Install','DIN Rail'],['Monitor','V/A/W/kWh']]},
  {brand:'tuya',id:'ty_presence_sensor',cat:'sensor',tag:'AI RADAR',tc:'green',name:'Human Presence Sensor',model:'Tuya HP222-Z',price:0,pd:'Contact for price',img:'presence_sensor',desc:'Advanced 60GHz radar sensor. Detects people even when still. Covers 24 sqm. Zigbee. Trigger lights, AC and automations automatically.',specs:[['Technology','60GHz Radar'],['Coverage','24 sqm'],['Detection','Presence + Motion'],['Protocol','Zigbee']]},
  {brand:'tuya',id:'ty_water_sensor',cat:'sensor',tag:'',tc:'',name:'Zigbee Water Leak Sensor',model:'Tuya WD100-Z',price:0,pd:'Contact for price',img:'water_sensor',desc:'Zigbee water leak detector. Real-time monitoring and instant push alert. Can auto-close water valve when leak detected. Battery powered.',specs:[['Protocol','Zigbee'],['Detection','Water Contact'],['Action','Scene Linkage'],['Install','Tool-free']]},
  {brand:'tuya',id:'ty_smart_plug',cat:'plug',tag:'MATTER',tc:'blue',name:'Matter Smart Plug EU 16A',model:'Tuya F1203-EU',price:0,pd:'Contact for price',img:'plug',desc:'Matter-certified smart plug. 16A max. Works with Alexa, Google, Apple HomeKit, SmartThings. Remote control, scheduling and power monitoring.',specs:[['Standard','Matter over Wi-Fi'],['Current','16A Max'],['Ecosystems','Alexa/Google/Apple/SmartThings'],['Monitor','Power (Optional)']]},
  {brand:'tuya',id:'ty_scene_switch',cat:'switch',tag:'',tc:'',name:'Smart Scene Switch',model:'Tuya PS162-W-EU',price:0,pd:'Contact for price',img:'smart_scence',desc:'WiFi scene switch to trigger multiple automations with one tap. Two-way and multi-way control. 16A output.',specs:[['Protocol','Wi-Fi + Bluetooth'],['Output','16A'],['Control','Multi-way Wireless'],['Sensor','Proximity Screen']]},
// ===== TUYA CAMERAS =====
  {brand:'tuya',id:'ty_cam_c23b_1',cat:'security',tag:'SMART KIT',tc:'blue',name:'Indoor Smart Camera Kit',model:'GS-C23B-1FSK',price:0,pd:'Contact for price',img:'ty_cam_c23b_1',desc:'Complete smart security kit with camera, infrared sensor, door sensor and remote controller. Supports Tuya Smart and Smart Life. Motion tracking, scene linkage and alarm.',specs:[['Resolution','2MP'],['Storage','Up to 256GB SD'],['Protocol','WiFi 2.4GHz'],['Compatible','Alexa / Google']]},
  {brand:'tuya',id:'ty_cam_c23b_2mp',cat:'security',tag:'',tc:'',name:'Indoor WiFi Camera 2MP',model:'GS-C23B-2MP',price:0,pd:'Contact for price',img:'ty_cam_c23b_2mp',desc:'2MP indoor WiFi camera. Single and dual-band WiFi support. Motion tracking, alarm linkage and app control via Tuya Smart.',specs:[['Resolution','2MP'],['WiFi','2.4GHz + 5GHz'],['Storage','Up to 256GB SD'],['Protocol','ONVIF']]},
  {brand:'tuya',id:'ty_cam_c23b_4mp',cat:'security',tag:'4MP',tc:'blue',name:'Indoor WiFi Camera 4MP',model:'GS-C23B-4MP',price:0,pd:'Contact for price',img:'ty_cam_c23b_4mp',desc:'4MP high resolution indoor camera. Dual-band WiFi, motion tracking, preset scene linkage. Alexa and Google Home compatible.',specs:[['Resolution','4MP'],['WiFi','2.4GHz + 5GHz'],['Storage','Up to 256GB SD'],['Compatible','Alexa / Google']]},
  {brand:'tuya',id:'ty_cam_c26_2mp',cat:'security',tag:'',tc:'',name:'Indoor PTZ Camera 2MP',model:'GS-C26-2MP',price:0,pd:'Contact for price',img:'ty_cam_c26_2mp',desc:'2MP pan-tilt indoor camera with motion tracking. Dual-band WiFi optional. Alarm sound settings and scene linkage.',specs:[['Resolution','2MP'],['WiFi','2.4GHz + 5GHz'],['Storage','Up to 256GB SD'],['Feature','Pan-Tilt']]},
  {brand:'tuya',id:'ty_cam_c26_4mp',cat:'security',tag:'4MP',tc:'blue',name:'Indoor PTZ Camera 4MP',model:'GS-C26-4MP',price:0,pd:'Contact for price',img:'ty_cam_c26_4mp',desc:'4MP pan-tilt indoor camera. Dual-band WiFi, ONVIF protocol, motion tracking and alarm linkage. Alexa and Google compatible.',specs:[['Resolution','4MP'],['WiFi','2.4GHz + 5GHz'],['Feature','Pan-Tilt + Tracking'],['Protocol','ONVIF']]},
  {brand:'tuya',id:'ty_cam_c11_2mp',cat:'security',tag:'COMPACT',tc:'green',name:'Mini Indoor Camera 2MP',model:'GS-C11-2MP',price:0,pd:'Contact for price',img:'ty_cam_c11_2mp',desc:'Compact mini indoor camera. Single and dual-band WiFi. Supports 2.4GHz, 5GHz and WiFi6. Siren and alarm tone settings.',specs:[['Resolution','2MP'],['WiFi','2.4GHz / 5GHz / WiFi6'],['Storage','Up to 256GB SD'],['Protocol','ONVIF']]},
  {brand:'tuya',id:'ty_cam_c11_4mp',cat:'security',tag:'COMPACT 4MP',tc:'blue',name:'Mini Indoor Camera 4MP',model:'GS-C11-4MP',price:0,pd:'Contact for price',img:'ty_cam_c11_4mp',desc:'4MP compact mini indoor camera. Dual-band WiFi including WiFi6. Alexa and Google Home compatible.',specs:[['Resolution','4MP'],['WiFi','2.4GHz / 5GHz / WiFi6'],['Storage','Up to 256GB SD'],['Compatible','Alexa / Google']]},
  {brand:'tuya',id:'ty_cam_c65_400w',cat:'security',tag:'OUTDOOR',tc:'green',name:'Outdoor PTZ Camera 4MP',model:'GS-C65-400W',price:0,pd:'Contact for price',img:'ty_cam_c65_400w',desc:'4MP outdoor PTZ camera with Bluetooth pairing. Supports up to 128GB SD. Siren settings, motion tracking and preset scene linkage.',specs:[['Resolution','4MP'],['Storage','Up to 128GB SD'],['Feature','Pan-Tilt-Zoom'],['Bluetooth','Pairing Support']]},
  {brand:'tuya',id:'ty_cam_c65_800w',cat:'security',tag:'OUTDOOR 8MP',tc:'gold',name:'Outdoor PTZ Camera 8MP',model:'GS-C65-800W',price:0,pd:'Contact for price',img:'ty_cam_c65_800w',desc:'8MP outdoor PTZ camera. Bluetooth pairing, siren, motion tracking and alarm linkage. Premium resolution for outdoor surveillance.',specs:[['Resolution','8MP'],['Storage','Up to 128GB SD'],['Feature','Pan-Tilt-Zoom'],['Bluetooth','Pairing Support']]},
  {brand:'tuya',id:'ty_cam_floodlight_3mp',cat:'security',tag:'FLOODLIGHT',tc:'gold',name:'Outdoor Floodlight Camera 3MP',model:'426-3M-TY',price:0,pd:'Contact for price',img:'ty_cam_floodlight_3mp',desc:'3MP outdoor floodlight camera with IR LEDs and white light. Alexa and Google compatible. PC support for computer view.',specs:[['Resolution','3MP'],['Lens','3.6mm'],['Lights','IR + White Floodlight'],['Compatible','Alexa / Google']]},
  {brand:'tuya',id:'ty_cam_floodlight_5mp',cat:'security',tag:'FLOODLIGHT 5MP',tc:'gold',name:'Outdoor Floodlight Camera 5MP',model:'426-5M-TY',price:0,pd:'Contact for price',img:'ty_cam_floodlight_5mp',desc:'5MP outdoor floodlight camera. IR and white LED floodlights, Tuya app, Alexa and Google support.',specs:[['Resolution','5MP'],['Lens','3.6mm'],['Lights','IR + White Floodlight'],['Compatible','Alexa / Google']]},
  {brand:'tuya',id:'ty_cam_ptz_3mp',cat:'security',tag:'OUTDOOR PTZ',tc:'blue',name:'Outdoor Mini PTZ Camera 3MP',model:'425-3M-TY',price:0,pd:'Contact for price',img:'ty_cam_ptz_3mp',desc:'1-inch mini PTZ outdoor camera. IP65 rated, IR LEDs, 3.6mm lens, 128GB SD support. Alexa and Google compatible.',specs:[['Resolution','3MP'],['Protection','IP65'],['Lens','3.6mm'],['Storage','Up to 128GB SD']]},
  {brand:'tuya',id:'ty_cam_ptz_5mp',cat:'security',tag:'OUTDOOR PTZ 5MP',tc:'gold',name:'Outdoor Mini PTZ Camera 5MP',model:'425-5M-TY',price:0,pd:'Contact for price',img:'ty_cam_ptz_5mp',desc:'5MP mini PTZ outdoor camera. IP65, IR LEDs, 128GB SD, Alexa and Google compatible.',specs:[['Resolution','5MP'],['Protection','IP65'],['Lens','3.6mm'],['Storage','Up to 128GB SD']]},
  {brand:'tuya',id:'ty_cam_solar_4mp',cat:'security',tag:'SOLAR ⭐',tc:'gold',name:'Solar WiFi PTZ Camera 4MP',model:'GS-42L-4MP',price:0,pd:'Contact for price',img:'ty_cam_solar_4mp',desc:'4MP solar powered outdoor PTZ camera. 4G + WiFi, human detection, motion detection, two-way audio. No wiring needed — fully solar powered.',specs:[['Resolution','4MP 1440P'],['Power','Solar + Battery'],['Detection','Human + Motion'],['Audio','Two-way']]},
  {brand:'tuya',id:'ty_cam_solar_light',cat:'security',tag:'SOLAR LIGHT',tc:'green',name:'Solar Security Camera + Light',model:'SS18M-3MP-TY',price:0,pd:'Contact for price',img:'ty_cam_solar_light',desc:'3MP solar security camera with integrated garden floodlight. Rotates 360°, IP66 rated, 5m extension cord. No wiring needed.',specs:[['Resolution','3MP'],['Power','Solar'],['Protection','IP66'],['Feature','360° Rotation']]},
  {brand:'tuya',id:'ty_cam_doorbell',cat:'security',tag:'VIDEO DOORBELL',tc:'blue',name:'Solar Video Doorbell',model:'GS-GD8-1',price:0,pd:'Contact for price',img:'ty_cam_doorbell',desc:'WiFi video doorbell with 180° lens, night vision, two-way intercom and solar charging. Human detection, 128GB SD support, IP66 waterproof.',specs:[['Resolution','4MP 1440P'],['Lens','180° Wide'],['Power','Solar + Battery'],['Protection','IP66']]},
  // ===== TUYA SMART CIRCUIT BREAKERS =====
  {brand:'tuya',id:'ty_breaker_1p_wifi',cat:'security',tag:'WIFI 1P',tc:'blue',name:'Smart Circuit Breaker 1P WiFi',model:'WCB-SC-1P100M-WIFI',price:0,pd:'Contact for price',img:'ty_breaker_1p_wifi',desc:'WiFi smart circuit breaker 1P 10A-100A with power meter. Remote on/off, real-time energy monitoring. Essential for Lebanon generator management.',specs:[['Poles','1P'],['Rating','10A–100A'],['Protocol','Wi-Fi 2.4GHz'],['Feature','Power Meter']]},
  {brand:'tuya',id:'ty_breaker_1p_zig',cat:'security',tag:'ZIGBEE 1P',tc:'green',name:'Smart Circuit Breaker 1P Zigbee',model:'WCB-SC-1P100M-ZIG',price:0,pd:'Contact for price',img:'ty_breaker_1p_zig',desc:'Zigbee smart circuit breaker 1P 10A-100A with power meter. More reliable than WiFi for critical circuits.',specs:[['Poles','1P'],['Rating','10A–100A'],['Protocol','Zigbee'],['Feature','Power Meter']]},
  {brand:'tuya',id:'ty_breaker_2p_wifi',cat:'security',tag:'WIFI 2P',tc:'blue',name:'Smart Circuit Breaker 2P WiFi',model:'WCB-SC-2P100M-WIFI',price:0,pd:'Contact for price',img:'ty_breaker_2p_wifi',desc:'WiFi smart circuit breaker 2P 10A-100A with power meter and electricity leakage protection. Remote control and energy monitoring.',specs:[['Poles','2P'],['Rating','10A–100A'],['Protocol','Wi-Fi 2.4GHz'],['Feature','Power Meter + Leakage Protection']]},
  {brand:'tuya',id:'ty_breaker_2p_zig',cat:'security',tag:'ZIGBEE 2P',tc:'green',name:'Smart Circuit Breaker 2P Zigbee',model:'WCB-SC-2P100M-ZIG',price:0,pd:'Contact for price',img:'ty_breaker_2p_zig',desc:'Zigbee smart circuit breaker 2P 10A-100A with power meter and leakage protection. Ideal for critical household circuits.',specs:[['Poles','2P'],['Rating','10A–100A'],['Protocol','Zigbee'],['Feature','Power Meter + Leakage Protection']]},
  {brand:'tuya',id:'ty_breaker_3p80_wifi',cat:'security',tag:'WIFI 3P',tc:'blue',name:'Smart Circuit Breaker 3P 80A WiFi',model:'WCB-SC-3P80-WIFI',price:0,pd:'Contact for price',img:'ty_breaker_3p80_wifi',desc:'WiFi smart circuit breaker 3P 10A-80A. Remote on/off and monitoring via app. Perfect for 3-phase panels.',specs:[['Poles','3P'],['Rating','10A–80A'],['Protocol','Wi-Fi 2.4GHz'],['Feature','Remote Control']]},
  {brand:'tuya',id:'ty_breaker_3p80_zig',cat:'security',tag:'ZIGBEE 3P',tc:'green',name:'Smart Circuit Breaker 3P 80A Zigbee',model:'WCB-SC-3P80-ZIG',price:0,pd:'Contact for price',img:'ty_breaker_3p80_zig',desc:'Zigbee smart circuit breaker 3P 10A-80A. Reliable Zigbee protocol for 3-phase smart panel setups.',specs:[['Poles','3P'],['Rating','10A–80A'],['Protocol','Zigbee'],['Feature','Remote Control']]},
  {brand:'tuya',id:'ty_breaker_3p100_wifi',cat:'security',tag:'WIFI 3P 100A',tc:'gold',name:'Smart Circuit Breaker 3P 100A WiFi',model:'WCB-SC-3P100-WIFI',price:0,pd:'Contact for price',img:'ty_breaker_3p100_wifi',desc:'High capacity WiFi smart circuit breaker 3P up to 100A. Ideal for heavy 3-phase loads and generator management.',specs:[['Poles','3P'],['Rating','Up to 100A'],['Protocol','Wi-Fi 2.4GHz'],['Feature','Remote Control']]},
  {brand:'tuya',id:'ty_breaker_3p100_zig',cat:'security',tag:'ZIGBEE 3P 100A',tc:'gold',name:'Smart Circuit Breaker 3P 100A Zigbee',model:'WCB-SC-3P100-ZIG',price:0,pd:'Contact for price',img:'ty_breaker_3p100_zig',desc:'High capacity Zigbee smart circuit breaker 3P up to 100A. Best for reliable 3-phase smart installations.',specs:[['Poles','3P'],['Rating','Up to 100A'],['Protocol','Zigbee'],['Feature','Remote Control']]},
  {brand:'tuya',id:'ty_breaker_4p80_wifi',cat:'security',tag:'WIFI 4P',tc:'blue',name:'Smart Circuit Breaker 4P 80A WiFi',model:'WCB-SC-4P80-WIFI',price:0,pd:'Contact for price',img:'ty_breaker_4p80_wifi',desc:'WiFi smart circuit breaker 4P 10A-80A. Full 4-pole control for complete smart panel management.',specs:[['Poles','4P'],['Rating','10A–80A'],['Protocol','Wi-Fi 2.4GHz'],['Feature','Remote Control']]},
  {brand:'tuya',id:'ty_breaker_4p80_zig',cat:'security',tag:'ZIGBEE 4P',tc:'green',name:'Smart Circuit Breaker 4P 80A Zigbee',model:'WCB-SC-4P80-ZIGBEE',price:0,pd:'Contact for price',img:'ty_breaker_4p80_zig',desc:'Zigbee smart circuit breaker 4P 10A-80A. Most reliable option for full 4-pole smart panel setups.',specs:[['Poles','4P'],['Rating','10A–80A'],['Protocol','Zigbee'],['Feature','Remote Control']]},
  // ===== SUMMAO CATALOG =====
  {brand:'summao',id:'sm_smart_plugs',cat:'plug',tag:'PORTABLE',tc:'blue',name:'Smart WiFi Plug Adapter',model:'SP-Series',price:0,pd:'Contact for price',img:'sm_plug_eu',desc:'Portable smart plug adapter. Turn any appliance into a smart device instantly. Supports scheduling and remote control via phone.',specs:[['Voltage','100-240V'],['Current','16A'],['Material','ABS+PC Fireproof'],['Life','25,000 Hours']],variants:[{name:'EU Plug',price:0,img:'sm_plug_eu',model:'Item 15'},{name:'UK Plug',price:0,img:'sm_plug_uk',model:'Item 13'},{name:'US Plug',price:0,img:'sm_plug_us',model:'Item 14'}]},
  {brand:'summao',id:'sm_wifi_breaker_10a',cat:'switch',tag:'DIY',tc:'green',name:'WiFi Smart Breaker (10A)',model:'Item 16',price:0,pd:'Contact for price',img:'sm_wifi_breaker',desc:'Small WiFi relay for basic light circuits or small appliances. Easy to hide in ceilings or boxes.',specs:[['Voltage','AC 100-240V'],['Max Load','10A'],['Material','ABS+PC Fireproof'],['Safety','94-v0 Fire Rating']]},
  {brand:'summao',id:'sm_mini_switch_16a',cat:'switch',tag:'MONITOR',tc:'gold',name:'WiFi Mini Switch + Power Monitor',model:'Item 17',price:0,pd:'Contact for price',img:'sm_mini_switch_mon',desc:'Ultra-small smart switch with built-in power monitoring. Fits behind your existing wall switch to track electricity usage.',specs:[['Voltage','AC 100-240V'],['Current','16A'],['Feature','Power Monitor'],['Life','25,000 Hours']]},
  {brand:'summao',id:'sm_wifi_bulb_rgb',cat:'lighting',tag:'RGB',tc:'gold',name:'Smart WiFi RGB Light Bulb',model:'Item 18',price:0,pd:'Contact for price',img:'sm_wifi_bulb',desc:'10W RGB smart bulb. Change colors, dim brightness, and sync with music from the app.',specs:[['Power','10W'],['Colors','RGB + White'],['Voltage','AC 85-265V'],['Control','WiFi App']]},
  {brand:'summao',id:'sm_lock_802pro',cat:'security',tag:'POPULAR',tc:'blue',name:'Smart Video Lock 802 Pro',model:'Sum-802pro',price:0,pd:'Contact for price',img:'sm_lock_802pro',desc:'Smart lock with built-in camera and Tuya WiFi. See who is at the door from your phone.',specs:[['Unlock','Camera, Fingerprint, App, Key'],['Power','8x AA Alkaline Battery'],['Material','Aluminum & Tempered Glass'],['App','Tuya / Smart Life']]},
  {brand:'summao',id:'sm_lock_907max',cat:'security',tag:'WATERPROOF',tc:'blue',name:'Automatic Waterproof Lock',model:'Sum-907Max',price:0,pd:'Contact for price',img:'sm_lock_907max',desc:'Fully automatic lock with waterproof front panel. Ideal for external doors and villas.',specs:[['Feature','IP65 Waterproof Front'],['Battery','Lithium-ion Rechargeable'],['Unlock','Face, Fingerprint, App, Card'],['Video','Live Video Calling']]},
  {brand:'summao',id:'sm_stg_touch',cat:'switch',tag:'GLASS TOUCH',tc:'gold',name:'Smart Glass Touch Switch',model:'STG Series',price:0,pd:'Contact for price',img:'sm_touch_1g',desc:'Luxury tempered glass touch switch. Available in 1 to 4 gangs to control all your lights.',specs:[['Voltage','110-240VAC'],['Load','3-300W/gang'],['Standard','EU/UK 86x86mm'],['WiFi','2.4GHz IEEE 802.11 b/g/n']],variants:{gangs:['1 Gang','2 Gang','3 Gang','4 Gang']},variantImgs:{'1 Gang_White':'sm_touch_1g','2 Gang_White':'sm_touch_2g','3 Gang_White':'sm_touch_3g','4 Gang_White':'sm_touch_4g'},variantPrices:{'1 Gang':'Contact for price','2 Gang':'Contact for price','3 Gang':'Contact for price','4 Gang':'Contact for price'}},
  {brand:'summao',id:'sm_combo_eu',cat:'plug',tag:'COMBO',tc:'blue',name:'Switch & EU Socket Combo',model:'STG-09/11',price:0,pd:'Contact for price',img:'sm_combo_eu_1g',desc:'Sleek glass panel combining smart switches with a high-power 16A EU socket.',specs:[['Socket','16A / 3500W Max'],['Standard','EU Type F'],['Size','146 x 86 mm'],['Material','Tempered Glass']],variants:{gangs:['1 Gang + Socket','2 Gang + Socket','3 Gang + Socket']},variantImgs:{'1 Gang + Socket_White':'sm_combo_eu_1g','2 Gang + Socket_White':'sm_combo_eu_2g','3 Gang + Socket_White':'sm_combo_eu_3g'},variantPrices:{'1 Gang + Socket':'Contact for price','2 Gang + Socket':'Contact for price','3 Gang + Socket':'Contact for price'}},
  {brand:'summao',id:'sm_combo_usb',cat:'plug',tag:'USB CHARGE',tc:'green',name:'Switch & USB Socket Combo',model:'STG-15/17',price:0,pd:'Contact for price',img:'sm_combo_usb_1g',desc:'Modern smart panel with switches, a universal socket, and dual USB ports for charging.',specs:[['USB Power','5V / 2.1A'],['Socket','13A Universal'],['Size','146 x 86 mm'],['Protection','Fireproof ABS/Glass']],variants:{gangs:['1 Gang + USB','2 Gang + USB','3 Gang + USB']},variantImgs:{'1 Gang + USB_White':'sm_combo_usb_1g','2 Gang + USB_White':'sm_combo_usb_2g','3 Gang + USB_White':'sm_combo_usb_3g'},variantPrices:{'1 Gang + USB':'Contact for price','2 Gang + USB':'Contact for price','3 Gang + USB':'Contact for price'}},
  {brand:'summao',id:'sm_heater_20a',cat:'switch',tag:'HIGH POWER',tc:'red',name:'Smart Water Heater Switch',model:'STG-05',price:0,pd:'Contact for price',img:'sm_heater_20a',desc:'Heavy-duty 20A switch for water heaters. Control your hot water from anywhere.',specs:[['Rated Power','4000W Max'],['Current','20A'],['Input','100-240VAC'],['Size','86 x 86 x 35mm']]},
  {brand:'summao',id:'sm_heavy_40a',cat:'switch',tag:'8000W MAX',tc:'red',name:'Ultra Power Smart Switch (40A)',model:'STGT-04-2',price:0,pd:'Contact for price',img:'sm_heavy_40a',desc:'The strongest smart switch for water pumps, large ACs, and industrial loads.',specs:[['Max Power','8000W'],['Current','40A'],['Voltage','AC 90-240V'],['App','Tuya / Smart Life']]},
  {brand:'summao',id:'sm_curtain_sw',cat:'curtain',tag:'AUTOMATION',tc:'green',name:'Smart Curtain Switch',model:'STGT-05',price:0,pd:'Contact for price',img:'sm_curtain_sw',desc:'Control motorized curtains or shutters from your phone. Supports percentage control.',specs:[['Power','2200W Max'],['Output','AC 90-240V'],['Design','Glass Touch'],['App','Tuya / Smart Life']]},
  {brand:'summao',id:'sm_lock_666',cat:'security',tag:'LUXURY',tc:'gold',name:'3D Face Recognition Lock',model:'Sum-666',price:0,pd:'Contact for price',img:'sm_lock_666',desc:'The ultimate security lock using 3D Face ID technology. Premium Gun Black finish.',specs:[['Technology','3D Face Recognition'],['Battery','5000mAh Rechargeable'],['Emergency','Micro USB Power Port'],['Video','Active Video Calling']]},
  {brand:'summao',id:'sm_lock_rim',cat:'security',tag:'GATE LOCK',tc:'green',name:'Smart Waterproof Rim Lock',model:'Sum-812-4',price:0,pd:'Contact for price',img:'sm_lock_rim',desc:'Specialized smart lock for garden gates and aluminum doors. Durable and waterproof.',specs:[['Type','Waterproof Rim Lock'],['Material','Aluminum & Stainless Steel'],['Unlock','Fingerprint, Card, App'],['App','Tuya / TTlock Support']]},
  {brand:'summao',id:'sm_lock_811',cat:'security',tag:'BEST VALUE',tc:'green',name:'Smart Classic Lock 811',model:'Sum-811',price:0,pd:'Contact for price',img:'sm_lock_811',desc:'Affordable and reliable smart lock. Perfect for standard wooden doors with full App control.',specs:[['Unlock','Fingerprint, Code, Card, Key'],['Power','4x AA Alkaline Battery'],['Material','Aluminum Alloy'],['App','Tuya / Smart Life']]},
  {brand:'summao',id:'sm_lock_937max',cat:'security',tag:'PREMIUM 3D',tc:'gold',name:'Luxury 3D Face Lock 937',model:'Sum-937Max',price:0,pd:'Contact for price',img:'sm_lock_937max',desc:'High-end 3D Face recognition with active video calling. Premium Mocha Gold or Gun Black finish.',specs:[['Technology','3D Face & Video Call'],['Battery','4200mAh Lithium-ion'],['Material','Aluminum Alloy'],['Unlock','Face, App, Code, Fingerprint']]},
  {brand:'summao',id:'sm_lock_929',cat:'security',tag:'SMART VALUE',tc:'blue',name:'3D Face ID Entry Lock',model:'Sum-929-3',price:0,pd:'Contact for price',img:'sm_lock_929',desc:'The most affordable way to get 3D Face Recognition for your home. Simple and secure.',specs:[['Technology','3D Face Recognition'],['Battery','3200mAh Lithium-ion'],['Material','Durable ABS'],['App','Wishome App Support']]},
  {brand:'summao',id:'sm_lock_608',cat:'security',tag:'SLIM DESIGN',tc:'red',name:'Narrow Frame Smart Lock',model:'Sum-608',price:0,pd:'Contact for price',img:'sm_lock_608',desc:'Specialized slim lock for aluminum or narrow-frame doors. Weather-resistant and durable.',specs:[['Special','Fits 92/72/85 Mortise'],['Width','Only 37mm Wide'],['Unlock','Fingerprint, App, Key'],['Protection','IP65 Weather Resistant']]}
];


// ============================================================
// FILTERS — Add a new brand here if you add a new brand
// ============================================================
const FILTERS = [
  {id:'all',en:'All',ar:'الكل'},
  {id:'sonoff',en:'Sonoff',ar:'Sonoff'},
  {id:'tuya',en:'Tuya',ar:'Tuya'},
  {id:'summao', en:'Summao', ar:'Summao'},
  {id:'switch',en:'Switches',ar:'مفاتيح'},
  {id:'plug',en:'Plugs',ar:'فيشات'},
  {id:'sensor',en:'Sensors',ar:'حساسات'},
  {id:'lighting',en:'Lighting',ar:'إضاءة'},
  {id:'security',en:'Security',ar:'أمان'},
  {id:'curtain',en:'Curtains',ar:'ستائر'},
  {id:'thermostat',en:'Thermostats',ar:'ثرموستات'},
];
